<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Help Videos") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th><?php echo $this->__("Help Topic") ?></th>
								<th width="20%"><?php echo $this->__("Action") ?></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><?php echo $this->__("Vendor Product") ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/help/view", array('path'=>'products-prohoods.m4v')) ?>"><?php echo $this->__("view") ?></a></td>
							</tr>
							<tr>
								<td><?php echo $this->__("Profile") ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/help/view", array('path'=>'profile-vendor.m4v')) ?>"><?php echo $this->__("view") ?></a></td>
							</tr>
							<tr>
								<td><?php echo $this->__("Purchase Order") ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/help/view", array('path'=>'purchase-order.m4v')) ?>"><?php echo $this->__("view") ?></a></td>
							</tr>
							<tr>
								<td><?php echo $this->__("Serial Number Status") ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/help/view", array('path'=>'serial_status.m4v')) ?>"><?php echo $this->__("view") ?></a></td>
							</tr>
							<tr>
								<td><?php echo $this->__("Vendor Employee") ?></td>
								<td><a href="<?php echo $this->getUrl("in	ventorymanager/help/view", array('path'=>'vendor-employee.m4v')) ?>"><?php echo $this->__("view") ?></a></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>