<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><?php echo $this->__("Vendor Section") ?></a> 
            </div>
            <?php if (Mage::getSingleton('inventorymanager/session')->isLoggedIn()) { ?>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> <!--Last access : 30 May 2014 &nbsp;--> 
  <a href="<?php echo $this->getUrl('inventorymanager/vendor/logout') ?>" class="btn btn-danger square-btn-adjust">
  	<?php echo $this->__("Logout") ?>
  </a>
  
</div>
<?php } ?>
        </nav>
<?php
	$currentController = $this->getRequest()->getControllerName();
	$currentAction = $this->getRequest()->getActionName();
	$productsPage = false;
	$dashboardPage = false;
	if($currentController == "vendor" && $currentAction == "products"){
		$productsPage = true;
	}elseif($currentController == "vendor" && $currentAction == "index"){
		$dashboardPage = true;
	}
?>
        
 <nav class="navbar-default navbar-side" role="navigation">
 <?php if (Mage::getSingleton('inventorymanager/session')->isLoggedIn()) { ?>
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
                    <img src="<?php echo $this->getSkinUrl("images/find_user.png") ?>" class="user-image img-responsive"/>
                    <?php echo $this->getLayout()->createBlock('inventorymanager/vendor_info')->setTemplate("inventorymanager/vendorinfo.phtml")->toHtml() ?>
					</li>
					
					
                    <li>
                        <a class="<?php if($dashboardPage) { echo "active-menu"; } ?>"  href="<?php echo $this->getUrl("inventorymanager/vendor/index") ?>"><i class="fa fa-dashboard fa-3x"></i> <?php echo $this->__("Dashboard") ?></a>
                    </li>
                    
                    <li>
                        <a class="<?php if($productsPage) { echo "active-menu"; } ?>"  href="<?php echo $this->getUrl("inventorymanager/vendor/products") ?>"><i class="fa fa-table fa-3x"></i> <?php echo $this->__("Products") ?></a>
                    </li>
                    
                     <li>
                        <a href="ui.html"><i class="fa fa-desktop fa-3x"></i><?php echo $this->__("Purchase Orders") ?></a>
                    </li>
                    <li>
                        <a  href="tab-panel.html"><i class="fa fa-qrcode fa-3x"></i><?php echo $this->__("Printing Labels") ?></a>
                    </li>
						   <li  >
                        <a   href="chart.html"><i class="fa fa-bar-chart-o fa-3x"></i> Morris Charts</a>
                    </li>	
                      <li  >
                        <a  href="table.html"><i class="fa fa-table fa-3x"></i> Table Examples</a>
                    </li>
                    <li  >
                        <a  href="form.html"><i class="fa fa-edit fa-3x"></i> Forms </a>
                    </li>				
					
					                   
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-3x"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                      </li>  
                  <li  >
                        <a  href="blank.html"><i class="fa fa-square-o fa-3x"></i> Blank Page</a>
                    </li>	
                </ul>
               
            </div>
            <?php } ?>
        </nav> 
        