<?php if (Mage::getSingleton('inventorymanager/session')->isLoggedIn()) { ?>	
<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><?php echo $this->__("Vendor Section") ?></a> 
            </div>
            
  <div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;"> <!--Last access : 30 May 2014 &nbsp;--> 
  <a href="<?php echo $this->getUrl('inventorymanager/vendor/logout') ?>" class="btn btn-danger square-btn-adjust">
  	<?php echo $this->__("Logout") ?>
  </a>
  
</div>
<?php }elseif(Mage::getSingleton('inventorymanager/session')->isAdminUser()){ ?>

<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><?php echo $this->__("Agent Section") ?></a> 
            </div>


	<div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;"> 
  <a href="<?php echo $this->getUrl('inventorymanager/adminuser/logout') ?>" class="btn btn-danger square-btn-adjust">
  	<?php echo $this->__("Logout") ?>
  </a>
  
</div>
<?php } ?>



        </nav>
<?php
	$currentController = $this->getRequest()->getControllerName();
	$currentAction = $this->getRequest()->getActionName();
	$productsPage = false;
	$dashboardPage = false;
	$printendLabel = false;
	$purchaseorderPage = false;
	$adminuserVendors = false;
    $manageVendors = false;
	$receiveProduct = false;
	$sendProduct = false;
	$sentSerials = false;
	$stockTab = false;
    $purchaseorder = false;
	$shippedProduct = false;
    
	if($currentController == "vendor" && $currentAction == "products"){
		$productsPage = true;
	}elseif($currentController == "vendor" && $currentAction == "index"){
		$dashboardPage = true;
	}elseif($currentController == "purchaseorder" && $currentAction == "grid"){
		$purchaseorderPage = true;
	}elseif($currentController == "label" && $currentAction == "find"){
		$printendLabel = true;
	}elseif($currentController == "adminuser" && $currentAction == "vendors"){
		$adminuserVendors = true;
	}elseif($currentController == "adminuser_serial" && ($currentAction == "findreceive" || $currentAction == "receive")){
		$receiveProduct = true;
	}elseif($currentController == "adminuser_serial" && ($currentAction == "find" || $currentAction == "send")){
		$sendProduct = true;
	}elseif($currentController == "adminuser_serial" && $currentAction == "sent"){ 
		$sentSerials = true;
	}elseif($currentController == "adminuser_serial" && $currentAction == "sent"){ 
		$sentSerials = true;
	}elseif($currentController == "adminuser_product" && ($currentAction == "stockgrid" || $currentAction == "serialgrid")){ 
		$stockTab = true;
	}elseif($currentController == "vendor_product" && ($currentAction == "stockgrid" || $currentAction == "serialgrid")){ 
		$shippedProduct = true;
	}elseif($currentController == "adminuser" && ($currentAction == "vendorprofiles" || $currentAction == "vendoredit")){ 
        $manageVendors = true;
    }
    elseif($currentController == "adminuser" && ($currentAction == "purchaseorder" || $currentAction == "edit")){ 
        $purchaseorder = true;
    }
?>
        
<nav class="navbar-default navbar-side" role="navigation">
<?php if (Mage::getSingleton('inventorymanager/session')->isLoggedIn()) { ?>
	<div class="sidebar-collapse">
		<ul class="nav" id="main-menu">
			<li class="text-center">
				<img src="<?php echo $this->getSkinUrl("images/find_user.png") ?>" class="user-image img-responsive"/>
				<?php echo $this->getLayout()->createBlock('inventorymanager/vendor_info')->setTemplate("inventorymanager/vendorinfo.phtml")->toHtml() ?>
			</li>
            <li>
                <a class="<?php if($dashboardPage) { echo "active-menu"; } ?>"  href="<?php echo $this->getUrl("inventorymanager/vendor/index") ?>">
                	<i class="fa fa-dashboard fa-3x"></i> <?php echo $this->__("Dashboard") ?>
                </a>
            </li>
            <li>
                <a class="<?php if($productsPage) { echo "active-menu"; } ?>"  href="<?php echo $this->getUrl("inventorymanager/vendor/products") ?>">
                	<i class="fa fa-table fa-3x"></i> <?php echo $this->__("Products") ?>
                </a>
            </li>   
			<li>
                <a class="<?php echo $purchaseorderPage?"active-menu":""; ?>" href="<?php echo $this->getUrl("inventorymanager/purchaseorder/grid") ?>">
                	<i class="fa fa-desktop fa-3x"></i>
                	<?php echo $this->__("Purchase Orders") ?>
                </a>
            </li>
            <li>
                <a class="<?php if($printendLabel) { echo "active-menu"; } ?>" href="<?php echo $this->getUrl('inventorymanager/label/find') ?>">
                	<i class="fa fa-qrcode fa-3x"></i><?php echo $this->__("Serial Number Status") ?>
                </a>
            </li>
            
            <li>
                <a class="<?php if($shippedProduct) { echo "active-menu"; } ?>" href="<?php echo $this->getUrl('inventorymanager/vendor_product/stockgrid') ?>">
                	<i class="fa fa-qrcode fa-3x"></i><?php echo $this->__("Stock in US") ?>
                </a>
            </li>
            
            <li>
                <a class="" href="#">
                	<i class="fa fa-edit fa-3x"></i><?php echo $this->__("Notifications") ?>
                </a>
            </li>
            
		</ul>           
	</div>
<?php }elseif(Mage::getSingleton('inventorymanager/session')->isAdminUser()){ ?>
	<div class="sidebar-collapse">
		<ul class="nav" id="main-menu">
			<li class="text-center">
				<img src="<?php echo $this->getSkinUrl("images/find_user.png") ?>" class="user-image img-responsive"/>
				<?php /* echo $this->getLayout()->createBlock('inventorymanager/vendor_info')->setTemplate("inventorymanager/vendorinfo.phtml")->toHtml()*/ ?>
			</li>
			<li>
                <a class="<?php echo $adminuserVendors?"active-menu":""; ?>"  href="<?php echo $this->getUrl("inventorymanager/adminuser/vendors") ?>">
                	<i class="fa fa-dashboard fa-3x"></i> <?php echo $this->__("Vendor Products") ?>
                </a>
            </li>
             <li>
                <a class="<?php echo $sendProduct?"active-menu":""; ?>"  href="<?php echo $this->getUrl("inventorymanager/adminuser_serial/find") ?>">
                	<i class="fa fa-table fa-3x"></i> <?php echo $this->__("Send Products") ?>
                </a>
            </li>
            <li>
                <a class="<?php echo $receiveProduct?"active-menu":""; ?>" href="<?php echo $this->getUrl("inventorymanager/adminuser_serial/findreceive") ?>">
                	<i class="fa fa-desktop fa-3x"></i>
                	<?php echo $this->__("Receive Products") ?>
                </a>
            </li>
            <?php /* <li>
                <a class="<?php echo $sentSerials?"active-menu":""; ?>" href="<?php echo $this->getUrl("inventorymanager/adminuser_serial/sent") ?>">
                	<i class="fa fa-desktop fa-3x"></i>
                	<?php echo $this->__("Send Serials") ?>
                </a>
            </li>*/ ?>
            <li>
                <a class="<?php if($stockTab) { echo "active-menu"; } ?>" href="<?php echo $this->getUrl('inventorymanager/adminuser_product/stockgrid') ?>">
                	<i class="fa fa-qrcode fa-3x"></i><?php echo $this->__("Stock") ?>
                </a>
            </li>
            <li>
               <a class="<?php echo $manageVendors?"active-menu":""; ?>"  href="<?php echo $this->getUrl("inventorymanager/adminuser/vendorprofiles") ?>">
                    <i class="fa fa-edit fa-3x"></i> <?php echo $this->__("Manage Vendors") ?>
                </a>
            </li>
            <li>
                <a class="<?php echo $purchaseorder?"active-menu":""; ?>"  href="<?php echo $this->getUrl("inventorymanager/adminuser_purchaseorder/index") ?>">
                    <i class="fa fa-square-o fa-3x"></i> <?php echo $this->__("Purchase Orders") ?>
                </a>
            </li>
		</ul>
	</div>
<?php } ?>
</nav>