<?php
	$orders = $this->getVendorOrders();
	$methods = Mage::getSingleton('shipping/config')->getActiveCarriers();
  	$shippingMethods = array();
  	foreach($methods as $_code => $_method)
 	{
 		if(!$_title = Mage::getStoreConfig("carriers/$_code/title")){
            $_title = $_code;
 		}
      	$shippingMethods[$_code] = $_title;
 	}
 	$paymentTerms = Mage::getModel('inventorymanager/paymentterms')->getArray();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Purchase Orders") ?></h2>
		<h5><?php ?></h5>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Purchase Order Grid") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					
						<table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
							<thead>
								<tr class="">
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">
										#
									</th>
									<th class="sorting_desc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 253px;" aria-label="Browser: activate to sort column ascending" aria-sort="descending">
										<?php echo $this->__("Shipping Method") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 229px;" aria-label="Platform(s): activate to sort column ascending">
										<?php echo $this->__("Payment Terms") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Order Qty") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1"  aria-label="CSS grade: activate to sort column ascending">
										<?php echo $this->__("Order Date") ?>
									</th>
								</tr>
							</thead>
							<tbody>
								<?php $iCounter = 0; foreach ($orders as $order) { ?>
									<?php
										$isOdd = true;
										if($iCounter%2==2){ $isOdd = false; }
										$iCounter++;
									?>
										<tr class="gradeA <?php echo $isOdd?"odd":"even"; ?>">
											<td><?php echo $order->getId() ?></td>
											<td><?php echo $shippingMethods[$order->getShippingMethod()] ?></td>
											<td><?php echo $paymentTerms[$order->getPaymentTerms()] ?></td>
											<td><?php echo $order->getOrderQty() ?></td>
											<td><?php echo $order->getDateOfPo() ?></td>
										</tr>
								<?php } ?>
							</tbody>
						</table>
						
					
				</div>
			</div>
		</div>
	</div>
</div>
<script>
    /*jQuery(document).ready(function () {
        jQuery('#dataTables-example').dataTable();
    });*/
</script>