<?php
	$serials = $this->getSerials();
?>
<div class="page">
	<nav style="margin-bottom: 0" role="navigation" class="navbar navbar-default navbar-cls-top ">
		<div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;"> 
  <a class="btn btn-danger square-btn-adjust" href="javascript:history.back()"><?php echo $this->__("Back") ?></a>
  
</div>
	</nav>
</div>
<div>
	<ul>
		<?php $iCounter = 1;
		$previousSerialProductId = 0; ?>
		<?php foreach ($serials as $serial){ ?>
		<?php
			if($previousSerialProductId != $serial->getProductId()){
				$productInfoObject = $this->getInventorymanagerProductInfo($serial->getId());
				$catalogProduct = $this->getCatalogProduct($serial->getId());
			}
			$previousSerialProductId = $serial->getProductId();
			$height = $catalogProduct->getHeight();
			$width = $catalogProduct->getWidth();
			$length = $catalogProduct->getLength();
			if($productInfoObject && $productInfoObject->getId()){
				$height = $productInfoObject->getHeight();
				$width = $productInfoObject->getWidth();
				$length = $productInfoObject->getLength();
			}
		?>
			<li style="border:1px solid #ccc;">
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td>
							<img src="<?php echo str_replace(array("index.php","index.php/"), "", Mage::getBaseUrl())	."barcode.php?text=".$serial->getSerial()."&size=32"; ?>" />
							<?php echo $serial->getSerial() ?>
						</td>
						<?php if($productInfoObject && $productInfoObject->getUpc() != ""){ ?>
						<td>
							<img src="<?php echo str_replace(array("index.php","index.php/"), "", Mage::getBaseUrl())	."barcode.php?text=".$productInfoObject->getUpc()."&size=32"; ?>" />
							<br/>
							<?php echo $productInfoObject->getUpc() ?>
						</td>
						<?php } ?>
					</tr>
					
				</table>
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td><?php echo $this->__("Product") ?></td>
						<td><?php echo $catalogProduct->getName() ?></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Weight") ?></td>
						<td><?php echo $catalogProduct->getWeight() ?></td>
					</tr>
				</table>
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td><?php echo $this->__("Height") ?></td>
						<td><?php echo $this->__("Width") ?></td>
						<td><?php echo $this->__("Depth") ?></td>
					</tr>
					<tr>
						<td><?php echo $height ?></td>
						<td><?php echo $width ?></td>
						<td><?php echo $depth ?></td>
					</tr>
					
				</table>
			</li>
			<li style="list-style: none"><br/><br/><br/></li>
		<?php } ?>
	</ul>
</div>