<?php
	$purchaseorderObject = $this->getPurchaseOrder();
	$methods = Mage::getSingleton('shipping/config')->getActiveCarriers();
  	$shippingMethods = array();
  	$locations = $this->helper('inventorymanager')->getLocations($purchaseorderObject->getVendorId());
  	foreach($methods as $_code => $_method)
 	{
 		if(!$_title = Mage::getStoreConfig("carriers/$_code/title")){
            $_title = $_code;
 		}
      	$shippingMethods[$_code] = $_title;
 	}
 	$paymentTerms = Mage::getModel('inventorymanager/paymentterms')->getArray(); 
?>
<div class="row">
	<div class="col-md-12">
		<h2>
			<?php echo $this->__("Purchase Order View") ?>
			<a class="btn btn-warning" href="<?php echo $this->getUrl("inventorymanager/label/generate", array('id'=>$purchaseorderObject->getId())) ?>" style="float:right"><?php echo $this->__("Generate") ?></a>
		</h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="panel panel-back noti-box">
			<table class="table table-striped">
				<tr>
					<td style="width:200px"><label><?php echo $this->__("Shipping Method") ?></label></td>
					<td><?php echo $shippingMethods[$purchaseorderObject->getShippingMethod()] ?></td>
				</tr>
				<tr>
					<td><label><?php echo $this->__("Payment Terms") ?></label></td>
					<td><?php echo $paymentTerms[$purchaseorderObject->getPaymentTerms()] ?></td>
				</tr>
				<tr>
					<td><label><?php echo $this->__("Order Date") ?></label></td>
					<td><?php echo date("Y-m-d", strtotime($purchaseorderObject->getDateOfPo())); ?></td>
				</tr>
				<?php if($purchaseorderObject->getExpectedDate() != ""){ ?>
				<tr>
					<td><label><?php echo $this->__("Order Date") ?></label></td>
					<td><?php echo date("Y-m-d", strtotime($purchaseorderObject->getExpectedDate())); ?></td>
				</tr>
				<?php } ?>
				<tr>
					<td><label><?php echo $this->__("Order Qty") ?></label></td>
					<td><?php echo $purchaseorderObject->getOrderQty(); ?></td>
				</tr>
				<tr>
					<td><label><?php echo $this->__("Received Qty") ?></label></td>
					<td><?php echo $purchaseorderObject->getReceivedQty(); ?></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Products") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th>#</th>
								<th><?php echo $this->__("Name") ?></th>
								<th><?php echo $this->__("Price") ?></th>
								<th><?php echo $this->__("Qty") ?></th>
								<th><?php echo $this->__("Total") ?></th>
								<th><?php echo $this->__("Action") ?></th>
							</tr>
						</thead>
						<tbody>
							<?php $iCounter = 0; foreach ($this->getProducts() as $product){
							$realProduct = Mage::getModel('catalog/product')->load($product->getMainProductId());
								?>
							<tr id="po_product_row_<?php echo $product->getId() ?>" class="ro_product_row clickable-row">
								<td><?php echo ++$iCounter; ?></td>
								<td><?php echo $realProduct->getName(); ?></td>
								<td><?php echo $product->getPrice(); ?></td>
								<td><?php echo $product->getQty(); ?></td>
								<td><?php echo $product->getTotal(); ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/purchaseorder/downloadproductpdf", array("order_id"=>$purchaseorderObject->getId(), "product_id"=>$product->getId()) ) ?>">
									<?php echo $this->__("Download PDF"); ?>
								</a></td>
							</tr>
							<?php $serials = $this->getSerials($product->getId()) ?>
							<tr id="serials_po_product_row_<?php echo $product->getId() ?>" style="display:none">
								<td colspan="6">
									<div class="panel panel-default" >
										<div class="panel-heading"><?php echo $this->__("Serials") ?></div>
										<div class="panel-body">
											<div class="table-responsive">
												<table class="table">
													<thead>
														<tr>
															<th><?php echo $this->__("Serial") ?></th>
															<th width="20%"><?php echo $this->__("Location") ?></th>
															<th width="20%"><?php echo $this->__("Action") ?></th>
														</tr>
													</thead>
													<tbody>
														<?php foreach ($serials as $serial){ ?>
															<tr>
																<td><a href="<?php echo $this->getUrl("inventorymanager/label/edit", array('serial_key'=>$serial->getSerial())); ?>"><?php echo $serial->getSerial() ?></a></td>
																<td>
																	<?php /*echo $serial->getLocation()*/ ?>
																	<select class="form-control" id="location_<?php echo $serial->getId() ?>">
																		<?php foreach ($locations as $key => $locationLabel) { ?>
																			<option <?php echo $serial->getLocation() == $locationLabel?"selected='selected'":""; ?>><?php echo $locationLabel ?></option>
																		<?php } ?>
																	</select>
																</td>
																<td><a class="btn btn-primary btn-sm" onclick="updateLocation(<?php echo $serial->getId() ?>)" href="javascript:void(0)"><?php echo $this->__("Update") ?></a></td>
															</tr>
														<?php } ?>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Comments") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th>#</th>
								<th><?php echo $this->__("Comment") ?></th>
								<th><?php echo $this->__("Date") ?></th>
								<th><?php echo $this->__("Attachement") ?></th>
							</tr>
						</thead>
						<tbody>
							<?php $iCounter = 0; foreach ($this->getComments() as $comment){ ?>
							<tr>
								<td><?php echo ++$iCounter; ?></td>
								<td><?php echo $comment->getComment(); ?></td>
								<td><?php echo $comment->getCreatedTime(); ?></td>
								<td>
									<a href="<?php echo $this->getUrl("inventorymanager/purchaseorder/download", array('file'=>$comment->getAttachement())) ?>"><?php echo $comment->getAttachement(); ?></a>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Small modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    	<div class="labelpage-loader-div">
      		<img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__("Loading...") ?>" />
      </div>
    </div>
  </div>
</div>
<script>
	$$("tr.ro_product_row").each(function(e){
		e.observe('click', function(){
			$('serials_' + e.id).toggle();
		});
	});
	function updateLocation(serialId){
		jQuery('.bs-example-modal-sm').modal('show');
		var location = $('location_' + serialId).value;
		new Ajax.Request('<?php echo $this->getUrl('inventorymanager/label/updatelocation') ?>', {
			method:'get',
			parameters: {serial_id:serialId, location:location},
  			onSuccess: function(transport) {
    			var response = transport.responseText;
    			jQuery('.bs-example-modal-sm').modal('hide');
    			if(response.length > 0)
    				alert(response);
  			},
  			onFailure: function() {
  				jQuery('.bs-example-modal-sm').modal('hide');
  				alert('Something went wrong...');
  			}
		});
	}
</script>