<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col1-layout" id="page-wrapper">
            <div class="main" id="page-inner">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
        <?php /*echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end')*/ ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
<script src="<?php echo $this->getSkinUrl("js/custom.js") ?>"></script>
<?php /*
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="<?php echo $this->getSkinUrl("uploader/js/jquery.knob.js");?> "></script>
<script src="<?php echo $this->getSkinUrl("uploader/js/jquery.ui.widget.js") ?>"></script>
<script src="<?php echo $this->getSkinUrl("uploader/js/jquery.iframe-transport.js") ?>"></script>
<script src="<?php echo $this->getSkinUrl("uploader/js/jquery.fileupload.js") ?>"></script>
<script src="<?php echo $this->getSkinUrl("uploader/js/script.js") ?>"></script> ****/ ?>

<!--<script src="http://cdn.tutorialzine.com/misc/enhance/v1.js" async></script> -->



</body>
</html>