<!-- New design start -->
<form id="comment-form" action="<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder_comment/post') ?>" method="POST" enctype="multipart/form-data">
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->__("Comments History") ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
					<fieldset>
						<div>
							<form id="comment-form" action="<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder_comment/post') ?>" method="POST" enctype="multipart/form-data">
								<div class="no-display">
									<input type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" name="form_key" />
									<input type="hidden" name="po_id" id="comment_po_id" value="<?php echo $this->getCurrentOrderId() ?>" />
								</div>
								<div class="order-history-form">
									<span class="field-row">
										<div class="row">
                            				<div class="col-md-4">
                            					<div class="form-group">
	            									<label for="status" class="normal"><?php echo $this->__("Status") ?></label><br>
	        										<select id="status" class="select form-control" name="status">
							                            <?php
							                            	$purchaseorderModel = $this->getCurrentOrder();
							                            	$statuses = Mage::getModel('inventorymanager/status')->getValues();
							                            	foreach ($statuses as $code => $label){
							                            ?>
					                            			<option value="<?php echo $code ?>" <?php echo $purchaseorderModel->getStatus() == $code?"selected='selected'":""; ?>>
					                            				<?php echo $label ?>
					                            			</option>
				                            			<?php } ?>
	                    							</select>
                    							</div>
                        					</div>
                        				</div>
                        				<div class="row">
                        					<div class="col-md-4">
                        						<div class="form-group">
	                        						<label for="attachement" class="normal"><?php echo $this->__("Attachement") ?></label>
	                        						<input type="file" class="" id="send_file" name="send_file" value="" onchange="uploadImage()">
	                        						<p id="uploaded_image_area"></p>
	                        					</div>
                        					</div>
                        				</div>
            							<div class="row">
            								<div class="col-md-12">
            									<div class="form-group">
            										<label for="history_comment" class="normal"><?php echo $this->__("Comment") ?></label>
            										<textarea id="history_comment" style="height:6em; width:99%;" class="form-control" cols="5" rows="3" name="comment"></textarea>
            									</div>
            								</div>
            							</div>
            							
            							<div class="row">
            								<div class="col-md-4">
            									<div class="form-group">
            										<button  onclick="subminComment()" class="scalable save btn btn-primary" type="button" title="<?php echo $this->__("Submit Comment") ?>">
            											<?php echo $this->__("Submit Comment") ?>
            										</button>
            									</div>
            								</div>
            							</div>
									
        							
            							
            						</div>
        							<div class="form-group">
	                            		<div class="table-responsive">
	                            			<?php
	                            				$comments = $this->getPurchaseOrderComments();
	                            			if($comments->count() > 0){ ?>
		                            			<table class="table table-striped table-bordered table-hover order-product-table">
		                            				<thead>
		                            					<tr>
		                            						<th width="20%"><?php echo $this->__("Date") ?></th>
		                            						<th width="50%"><?php echo $this->__("Comment") ?></th>
		                            						<th width="20%"><?php echo $this->__("Attachement") ?></th>
		                            						<th width="10%"><?php echo $this->__("Action") ?></th>
		                            					</tr>
		                            				</thead>
		                            				<tbody id="comments_list">
		                            					<?php foreach ($comments as $comment){ ?>
		                            					<tr>
		                            						<td><?php echo date("M d, Y h:i:s a",strtotime($comment->getCreatedTime())); ?></td>
		                            						<td><?php echo $comment->getComment(); ?></td>
		                            						<td>
		                            							<?php  if($comment->getAttachement() != ""){ ?>
		                            								<a class="subdue orderspro-file" href="<?php echo $this->getUrl("inventorymanager/adminuser_purchaseorder_comment/download", array("id"=>$comment->getId())) ?>">
																		<?php echo $comment->getAttachement() ?>
																	</a>
		                            							<?php } ?>
		                            						</td>
		                            						<td align="center" valign="bottom"><a class="btn btn-danger" onclick="deleteComment(<?php echo $comment->getId() ?>); return false;" href="javascript:void(0)">X</a></td>
		                            					</tr>
		                            					<?php } ?>
		                            				</tbody>
		                            			</table>
	                            			<?php } ?>
	                            		</div>
	                            	</div>
								</div>
							</div>
						</fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
</form>
<script>
      function uploadImage(){
      	
      	return;
      	
      	jQuery("#comment-form").on('submit',(function(e) {
		e.preventDefault();
		jQuery.ajax({
        	url: "<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder_comment/ajaxUpload') ?>",
			type: "POST",
			data:  new FormData(this),
			contentType: false,
    	    cache: false,
			processData:false,
			success: function(data)
		    {
			//$("#targetLayer").html(data);
		    },
		  	error: function() 
	    	{
	    	} 	        
	   });
	}));
      	
      	
      	
      	
      	
      	
       /* jQuery('#comment-form').bind('submit', function () {
          jQuery.ajax({
            type: 'post',
            url: '<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder_comment/ajaxUpload') ?>',
            data:jQuery('#comment-form').serialize(),
            success: function () {
              alert('form was submitted');
            }
          });
          return false;
        });*/
      }
    </script>
<script>

function subminComment(){
	var purchseorderId = $('comment_po_id').value ;
	if(purchseorderId == "" || purchseorderId <= 0){
		alert('<?php echo $this->__("Comments can not add without ourder got saved") ?>');
		return false;
	}
	var conf = confirm("<?php echo $this->__("Please confirm. All data that hasn't been saved will be lost.") ?>");
	if(conf){
		$("comment-form").submit();
	}
}

	/*function subminComment(){
		return ;
		var comment = $('history_comment').value;
		
		var poId = $('comment_po_id').value
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("inventorymanager/adminuser_purchaseorder_comment/post") ?>', {
			method:'post',
			parameters: {po_id: poId, comment : comment},
  			onSuccess: function(transport) {
    			var response = transport.responseText || "no response text";
    			$('history_comment').value = '';
    			refreshList();
  			},
  			onFailure: function() { alert('Something went wrong...'); }
		});
	}*/
	
	function refreshList(){
		var poId = $('comment_po_id').value
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("inventorymanager/adminuser_purchaseorder_comment/refresh") ?>', {
			method:'post',
			parameters: {id: poId},
  			onSuccess: function(transport) {
    			var response = transport.responseText || "no response text";
    			$('comments_list').innerHTML = response;
  			},
  			onFailure: function() { alert('Something went wrong...'); }
		});
	}
	
	function deleteComment(id){
		var conf = confirm("<?php echo $this->__("Are you sure want to delete the comment?") ?>");
		if(!conf){
			return;
		}
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("inventorymanager/adminuser_purchaseorder_comment/remove") ?>', {
			method:'post',
			parameters: {id: id},
  			onSuccess: function(transport) {
    			var response = transport.responseText || "no response text";
    			//$('comments_list').innerHTML = response;
    			refreshList();
  			},
  			onFailure: function() { alert('Something went wrong...'); }
		});
	}
	
	/*function uploadFile(){
		new Ajax.UploadRequest('', 'send_file', {
		  progress: 'ProgressElement',
		  onUpload: function (data) {
		    if (data.lengthComputable)
		      // Displaying percent uploaded, draw a progress bar, etc...
		      this.progress.update(Math.floor(100 * data.loaded / data.total));
		  },
		  onSuccess: function () {
		    this.progress.update('Done');
		  }
		});
	}*/
</script>