<?php
	$c_vendorId = "";
	$c_shippingMethod = "";
	$c_paymentTerms = "";
	$c_dateOfPo = "";
	$c_expectedDate = "";
	if($currentPurchaseOrder = $this->getCurrentOrder()){
		$c_vendorId = $currentPurchaseOrder->getVendorId();
		$c_shippingMethod = $currentPurchaseOrder->getShippingMethod();
		$c_paymentTerms = $currentPurchaseOrder->getPaymentTerms();
		$c_dateOfPo = $currentPurchaseOrder->getDateOfPo();
		$c_expectedDate = $currentPurchaseOrder->getExpectedDate();
	}
?>


<!-- New design start -->

<div class="row">
    <div class="col-md-12">
        <h2>
        	<?php if($this->getCurrentOrder()):?>
						<?php echo $this->__("Edit Purchase Order") ?>
			<?php else:?>
						<?php echo $this->__("Add Purchase Order") ?>
			<?php endif;?>
		</h2>
        <div style="float:right;padding-right:10px">
             <button type="button" onclick='document.getElementById("edit_form").submit();' title="<?php echo "<?php echo $this->__('Save');?>";?>" class="btn btn-warning" ><span><span><?php echo "Save";?></span></span></button>
        </div>
        <?php if($this->getCurrentOrder()): ?>
				<div style="float:right;padding-right:10px">
					<button style="" onclick="setLocation('<?php echo $this->getUrl("inventorymanager/adminuser_purchaseorder/generatePdf", array('id'=>$this->getCurrentOrder()->getId()) ) ?>');" class="btn btn-warning" type="button" title="<?php echo $this->__("Download PDF") ?>">
						<span><span><span><?php echo $this->__("Download PDF") ?></span></span></span>
					</button>
				</div>
		<?php endif; ?>	
    </div>
</div>
<hr>



<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->__("Fill below information") ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                    	<form id="edit_form" name="edit_form" enctype="multipart/form-data" method="post" action="<?php echo $this->getUrl("inventorymanager/adminuser_purchaseorder/save") ?>">
                        <?php echo $this->getMessagesBlock()->toHtml() ?>
	                        <div class="no-display">
								<input type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" name="form_key" />
								<?php if($this->getCurrentOrder()): ?>
									<input type="hidden" value="<?php echo $currentPurchaseOrder->getId() ?>" name="id" />
								<?php endif; ?>
								<input type="hidden" value="" id="save_back" name="back" />
							</div>
							<div class="row">
								<div class="col-md-6">
		                            <div class="form-group">
		                                <label for="name"><?php echo $this->__('Name');?><span class="required">*</span></label>
		                                <select id="vendor_id" name="vendor_id" class="required-entry select form-control">
											<?php foreach ($this->getVendors() as $vendorId => $vendorName): ?>
												<option value="<?php echo $vendorId ?>" <?php echo $c_vendorId==$vendorId?"selected='seleted'":""; ?> ><?php echo $vendorName ?></option>
											<?php endforeach; ?>
										</select>
		                            </div>
		
		                            <div class="form-group">
		                                <label><?php echo $this->__("Shipping Mehtod") ?></label>
		                                <select id="shipping_method" name="shipping_method" class="required-entry select form-control">
											<?php foreach ($this->getAllShippingMethod() as $code => $title): ?>
												<option value="<?php echo $code ?>" <?php echo $c_shippingMethod==$code?"selected='selected'":""; ?>  ><?php echo $title ?></option>
											<?php endforeach; ?>
										</select>
		                            </div>
		                            
		                            <div class="form-group">
		                                <label><?php echo $this->__("Payment Terms") ?></label>
		                               	<select id="payment_terms" name="payment_terms" class="required-entry select form-control">
											<?php foreach ($this->getPaymentTerms() as $code => $title): ?>
											<option value="<?php echo $code ?>" <?php echo $c_paymentTerms==$code?"selected='selected'":""; ?>><?php echo $title ?></option>
											<?php endforeach; ?>
										</select>
		                            </div>
		                        </div>
	                        </div>
                            <div class="row">
								<div class="col-md-6">
	                            	<div class="form-group">
	                                	<label><?php echo $this->__("Date Of Purchase Order") ?></label>
	                                	<div class="form-group input-group">
	                                		<input type="text" class=" input-text required-entry form-control" title="<?php echo $this->__("Date Of Purchase Order") ?>" value="<?php echo $c_dateOfPo!=""?date('d/m/Y', strtotime($c_dateOfPo)):date('d/m/Y'); ?>" id="date_of_po" name="date_of_po">
	                                		<span class="input-group-addon">
												<img style="" title="<?php echo $this->__("Select Date") ?>" id="date_of_po_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif") ?> ">
											</span>
										</div>
	                            	</div>
									<div class="form-group">
	                                	<label><?php echo $this->__("Expted Date") ?></label>
	                                	<div class="form-group input-group">
	                                		<input type="text"  class=" input-text form-control" title="<?php echo $this->__("Expted Date") ?>" value="<?php echo $c_expectedDate!=""?date('d/m/Y', strtotime($c_expectedDate)):date('d/m/Y', strtotime('+30 days')); ?>" name="expected_date" id="expected_date">
	                                		<span class="input-group-addon">
												<img style="" title="<?php echo $this->__("Select Date") ?>" id="expected_date_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif") ?> ">
											</span>
										</div>
	                            	</div>
	                          	
	                            	<div class="form-group">
	                                	<label><?php echo $this->__("Add Product to purchase order") ?></label>
	                                	<div class="form-group input-group">
	                                		<input type="text" class="input-text form-control" id="add_product"   />
	                                		<span class="input-group-btn">
												<button type="button" onclick="loadProducts()" class="btn btn-default"><i class="fa fa-search"></i></button>
											</span>
	                                	</div>
										<!--<div id="product_suggestion_box"></div>-->
	                            	</div>
                            	</div>
							</div>
							<div class="form-group">
	                            <div class="table-responsive">
	                            	<table class="table table-striped table-bordered table-hover order-product-table">
	                            		<thead>
	                            			<tr>
	                            				<th><?php echo $this->__("Name") ?></th>
	                            				<th><?php echo $this->__("Qty") ?></th>
	                            				<th><?php echo $this->__("Price/Unit") ?></th>
	                            				<th><?php echo $this->__("Total") ?></th>
	                            				<th><?php echo $this->__("Remove") ?></th>
	                            			</tr>
	                            		</thead>
	                            		<tbody id="products_grid">
	                            			<?php if($this->getCurrentOrder()) { ?>
		                            			<?php
		                            				$orderedUnits = 0;
		                            				$orderTotal = 0;
		                            			 	foreach ($this->getCurrentOrderProducts() as $orderProduct){ ?>
		                            				<?php $productObject = Mage::getModel('catalog/product')->load($orderProduct->getMainProductId()); ?>
		                            				<?php
		                            					$orderTotal += $orderProduct->getTotal();
		                            					$orderedUnits += $orderProduct->getQty();
		                            				?>
		                            				<tr class="order-row">
		                            					<td>
		                            						<?php echo $productObject->getName() ?>
															<input type="hidden" class="" name="po_product[]" value="<?php echo $orderProduct->getId() ?>" />
															<input type="hidden" class="order_product_hidden_input"  value="<?php echo $productObject->getId() ?>" />
		                            					</td>
		                            					<td>
		                            						<?php echo $orderProduct->getQty() ?>
															<input type="text" value="<?php echo $orderProduct->getQty() ?>" name="qty[<?php echo $productObject->getId() ?>]" class="input-text input-qty form-control" onchange="countTotal()" />
		                            					</td>
		                            					<td>
		                            						<?php echo $orderProduct->getPrice() ?>
															<input type="text" value="<?php echo $orderProduct->getPrice() ?>" name="product_value[<?php echo $productObject->getId() ?>]" class="input-text input-price form-control" onchange="countTotal()" />
		                            					</td>
		                            					<td class="row-total p-input"><?php echo $orderProduct->getTotal(); ?></td>
		                            					<td align="center" valign="bottom"><a class="btn btn-danger" onclick="removeProduct(this)">X</a></td>
		                            				</tr>
		                            			<?php }?>
	                            			<?php }?>
	                            		</tbody>
	                            		<tfoot>
	                            			<tr>
	                            				<td colspan="3" align="right"><b><?php echo $this->__("Units Ordered") ?></b></td>
	                            				<td colspan="2" align="right"><span id="total_qty"><?php echo $orderedUnits ?></span></td>
	                            			</tr>
	                            			<tr>
	                            				<td colspan="3" align="right"><b><?php echo $this->__("Units Received") ?></b></td>
	                            				<td colspan="2" align="right"><span id="total_qty_received"></span></td>
	                            			</tr>
	                            			<tr>
	                            				<td colspan="3" align="right"><b><?php echo $this->__("Total") ?></b></td>
	                            				<td colspan="2" align="right"><span id="grant_total"><?php echo number_format($orderTotal, 2); ?></span></td>
	                            			</tr>
	                            		</tfoot>
	                            	</table>
	                            </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
					<div class="col-md-12">
                    	<?php echo $this->getChildHtml('adminuser.purchaseorder.edit.comment') ?>
                    </dir>
             	</div>
            </div>
        </div>
    </div>    
</div>
<!-- Small modal -->
<div class="modal fade bs-example-modal-sm">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" onclick="jQuery('.bs-example-modal-sm').modal('hide');" ><span>&times;</span></button>
        <h4 class="modal-title"><?php echo $this->__("Resulted Products") ?></h4>
      </div>
      <div class="modal-body purchaseorder-product-result" id="product_suggestion_box">
        
      </div>
      <div class="labelpage-loader-div" id="loading-div">
      		<img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__("Loading...") ?>" />
      	</div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
			
	


<!-- New design end -->


<script type="text/javascript">
    editForm = new varienForm('edit_form','');
    
</script>

<script type="text/javascript">// <![CDATA[
Calendar.setup({
    inputField : 'date_of_po',
    ifFormat : '%m/%d/%Y',
    button : 'date_of_po_trig',
    align : 'Bl',
    singleClick : true
});

Calendar.setup({
    inputField : 'expected_date',
    ifFormat : '%m/%d/%Y',
    button : 'expected_date_trig',
    align : 'Bl',
    singleClick : true
});
// ]]>
</script>
<script>



	function loadProducts(){
		var keyword = $('add_product').value;
		if(keyword == "") return ;
		var vendorId = $('vendor_id').value;
		if(vendorId == "") return;
		jQuery('.bs-example-modal-sm').modal('show');
		$('loading-div').show();
		$('product_suggestion_box').hide();
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("inventorymanager/adminuser_purchaseorder/findproduct") ?>', {
			method:'post',
			parameters: {keyword: keyword, vendor_id : vendorId}, 
  			onSuccess: function(transport) {
  			//	$('product_suggestion_box').show();
    			var response = transport.responseText || "no response text";
    			$('loading-div').hide();
    			$('product_suggestion_box').show();
    			$('product_suggestion_box').innerHTML = response;
  			},
  			onFailure: function() { alert('Something went wrong...'); }
		});
	}
	
	
	function addProduct(pid,ele){
		var canRun = true;
		$$('.order_product_hidden_input').each(function(e){
			if(e.value == pid){
				var innerText = ele.down('a').innerHTML;
				ele.innerHTML = '<a>'+innerText+'</a> - <?php echo $this->__("Product already exist") ?>';
				canRun = false;
				throw $break;
			}
		});
		if(!canRun){ return false; }
		//$('product_suggestion_box').hide();
		$('loading-div').show();
		$('product_suggestion_box').hide();
		
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("inventorymanager/adminuser_purchaseorder/getproductinfo") ?>', {
			method:'post',
			parameters: {product_id: pid},
  			onSuccess: function(transport) {
    			var response = transport.responseText || "no response text";
    			jQuery('.bs-example-modal-sm').modal('hide');
    			$('products_grid').insert(response);
    			countTotal();
  			},
  			onFailure: function() { alert('Something went wrong...'); }
		});
	}
	
	
	function countTotal(element){
		var finalQty = 0;
		var finalTotal = 0;
		$$('.order-row').each(function(e){
			var rowQty = e.down('.input-qty').value;
			var rowPrice = e.down('.input-price').value;
			var rowTotal = rowPrice * rowQty;
			e.down('.row-total').innerHTML = Number(rowTotal).toFixed(2);
			finalQty += parseInt(rowQty);
			finalTotal += parseInt(rowTotal);
		});
		$('grant_total').innerHTML = Number(finalTotal).toFixed(2);
		$('total_qty').innerHTML = finalQty;
	}
	
	function removeProduct(element){
		element.up('tr').remove();
		countTotal();
	}
	countTotal();
	
	//countGTotal();
	//countQty();
	
</script>
