<?php $products = $this->getMatchingProduct(); ?>

<?php /* 
<ul>
<?php if($products->count() > 0){ ?>
	<?php foreach ($products as $product){ ?>
		<li  onclick="addProduct(<?php echo $product->getId() ?>, this)">
			<a><?php echo $product->getName(); ?></a>
		</li>
	<?php } ?>

<?php }else{ ?>
	<li><?php echo $this->__("No matching product found for this vendor") ?></li>
<?php } ?>
</ul> */ ?>
<select class="select form-control selectpicker show-select" id="select-picker-product" onchange="addProduct(this.value, this.options[this.selectedIndex].innerHTML)">
	<option value=""><?php echo $this->__("Select Product") ?></option>>
	<?php foreach ($products as $product){ ?>
		<option value="<?php echo $product->getId() ?>"><?php echo $product->getName() ?></option>
	<?php } ?>
</select>