<?php
	$serials = $this->getSerials();
	
	
	$_helper = $this->helper('catalog/output');
?>

<div>
	<ul>
		<?php $iCounter = 1 ?>
		<?php $previousSerialProductId = 0; ?>
		<?php foreach ($serials as $serial){ ?>
		<?php
			if($previousSerialProductId != $serial->getProductId()){
				$productInfoObject = $this->getInventorymanagerProductInfo($serial->getId());
				$catalogProduct = $this->getCatalogProduct($serial->getId());
			}
			$previousSerialProductId = $serial->getProductId();
			$height = $catalogProduct->getHeight();
			$width = $catalogProduct->getWidth();
			$length = $catalogProduct->getLength();
			if($productInfoObject && $productInfoObject->getId()){
				
				$boxWidth = $productInfoObject->getBoxWidth();
				$boxHeight = $productInfoObject->getBoxHeight();
				$boxLength = $productInfoObject->getBoxLength();
				
				if($productInfoObject->getHeight() && $productInfoObject->getHeight() > 0){
					$height = $productInfoObject->getHeight();
				}
				if($productInfoObject->getWidth() && $productInfoObject->getWidth() > 0){
					$width = $productInfoObject->getWidth();
				}
				if($productInfoObject->getLength() && $productInfoObject->getLength() > 0){
					$depth = $productInfoObject->getLength();
				}
			}
		?>
		<?php for($ic=0;$ic<2;$ic++) {?>
			<li style="border:1px solid #ccc;">
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td>
							<?php echo $serial->getSerial() ?>
						</td>
					</tr>
					<tr>
						<td>
							<img src="<?php echo str_replace(array("index.php","index.php/"), "", Mage::getBaseUrl())	."barcode.php?text=".$serial->getSerial()."&size=32"; ?>" />
							
						</td>
					</tr>
					<?php if($product->getMainImage() != "") { ?>
						<td colspan="3">
							<img src="<?php echo $this->helper("inventorymanager")->resizeImage($product->getMainImage(), 100, 100, "label/"); ?>" />
						</td>
						<?php }elseif ($catalogProduct->getImage() != "" && $catalogProduct->getImage() != "no_selection"){ ?>
							<td colspan="3">
								<img src="<?php echo $this->helper('catalog/image')->init($catalogProduct, 'image')->resize(100); ?>" />
							</td>
						<?php } ?>
						<?php if($productInfoObject && $productInfoObject->getUpc() != ""){ ?>
						<tr>
							<td>
							<!--<img src="<?php /*echo str_replace(array("index.php","index.php/"), "", Mage::getBaseUrl())	."barcode.php?text=".$productInfoObject->getUpc()."&size=32";*/ ?>" />-->
							
							<?php echo $productInfoObject->getUpc() ?>
							</td>
						</tr>
						<?php } ?>
					
					
				</table>
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td><?php echo $this->__("Product") ?></td>
						<td><?php echo $catalogProduct->getName() ?></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Weight") ?></td>
						<td><?php echo $catalogProduct->getWeight() ?></td>
					</tr>
				</table>
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td><?php echo $this->__("Height") ?></td>
						<td><?php echo $this->__("Width") ?></td>
						<td><?php echo $this->__("Depth") ?></td>
					</tr>
					<tr>
						<td><?php echo $height ?></td>
						<td><?php echo $width ?></td>
						<td><?php echo $depth ?></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Box Height") ?></td>
						<td><?php echo $this->__("Box Width") ?></td>
						<td><?php echo $this->__("Box Depth") ?></td>
					</tr>
					<tr>
						<td><?php echo $boxHeight ?></td>
						<td><?php echo $boxWidth ?></td>
						<td><?php echo $boxLength ?></td>
					</tr>
				</table>
			</li>
			<li style="list-style: none"><br/><br/><br/></li>
		<?php } ?>
		<?php } ?>
	</ul>
</div>