<?php $currentOrder = $this->getCurrentOrder(); ?>
<?php $vendor = Mage::getModel('inventorymanager/vendor')->load($currentOrder->getVendorId()); ?>
<?php $shippingMethods = $this->getAllShippingMethod(); ?>
<?php $allPaymentTerms = $this->getPaymentTerms();  ?>
<table>
	<tr>
		<td>
			<h2 style="font-size:28px;"><?php echo $this->__("Purchase Order") ?></h2>
			<br/>
		</td>
	</tr>
	<tr>
		<td>
			<table border="1" cellpadding="5"  width="350">
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Vendor") ?></td>
					<td><?php echo $vendor->getName() ?></td>
				</tr>
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Shipping Method") ?></td>
					<td><?php echo $shippingMethods[$currentOrder->getShippingMethod()] ?></td>
				</tr>
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Payment Terms") ?></td>
					<td><?php echo $allPaymentTerms[$currentOrder->getPaymentTerms()] ?></td>
				</tr>
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Purchase Order Date") ?></td>
					<td><?php echo date('d/m/Y', strtotime($currentOrder->getDateOfPo())) ?></td>
				</tr>
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Expected Date") ?></td>
					<td><?php echo date('d/m/Y', strtotime($currentOrder->getExpectedDate())) ?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
		<br/>
			<h2>Order Products</h2>
			<table cellpadding="5" cellspacing="1"  border="1">
				<tr>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Name") ?></td>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Qty") ?></td>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Unite Cost") ?></td>
					<td bgcolor="#DFE8F5"><?php echo $this->__("Total") ?></td>
				</tr>
				<?php $grandTotal = 0; ?>
				<?php $totalQty = 0; ?>
				<?php foreach ($this->getCurrentOrderProducts() as $orderProduct){ ?>
					<?php $productModel = Mage::getModel('catalog/product')->load($orderProduct->getMainProductId()) ?>
					<?php $grandTotal += $orderProduct->getTotal() ?>
					<?php $totalQty += $orderProduct->getQty() ?>
					<tr>
						<td><?php echo $productModel->getName() ?></td>
						<td align="right"><?php echo $orderProduct->getQty() ?></td>
						<td align="right"><?php echo $orderProduct->getPrice() ?></td>
						<td align="right"><?php echo $orderProduct->getTotal() ?></td>
					</tr>
				<?php } ?>
				<tr>
					<td></td>
					<td align="right"><?php echo $totalQty ?></td>
					<td align="right" bgcolor="#DFE8F5"><b>Total</b></td>
					<td align="right"><?php echo $grandTotal ?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="right">
			<br/>
			<br/>
			<br/>
			<br/>
			<?php echo $this->__("Thank You") ?>
		</td>
	</tr>
</table>