<script>

function compareScan()
    {
	var barcode = KC_value;
        var mode = '';
        if (document.getElementById('scan_1').innerHTML == '')
            mode = 'first_scan';
        else
        {
            if (document.getElementById('scan_2').innerHTML == '')
                mode = 'second_scan';
            else
                mode = 'first_scan';
        }


        //apply mode
        switch(mode)
        {
            case 'first_scan':
		document.getElementById('scan_1').innerHTML = barcode
                document.getElementById('scan_2').innerHTML = '';
                document.getElementById('result').innerHTML = '';
		KC_value = '';
                break;
            case 'second_scan':
                document.getElementById('scan_2').innerHTML = barcode
                if(document.getElementById('scan_1').innerHTML != '' && document.getElementById('scan_2').innerHTML != '')
			if (document.getElementById('scan_1').innerHTML == document.getElementById('scan_2').innerHTML)
                    		document.getElementById('result').innerHTML = '<font color="green">OK</front>';
                	else
                    		document.getElementById('result').innerHTML = '<font color="red">ERROR</front>';
                break;
        }


 //       resetHandledKey();
    }

//**************************** written by Sanjiv Pant *******
function codeComparer(barCodeVal){

	if (document.getElementById('scan_1').innerHTML == '' || (document.getElementById('scan_1').innerHTML != '' && document.getElementById('scan_2').innerHTML != '')){
	//alert('nous sommes dedans la fonction');
		if(barCodeVal.indexOf('\n') != -1||barCodeVal.indexOf('\r') != -1){
			document.getElementById('scan_1').innerHTML = barCodeVal;
			if ((document.getElementById('scan_1').innerHTML != '' && document.getElementById('scan_2').innerHTML != ''))
				document.getElementById('scan_2').innerHTML = '';
                        document.getElementById('result').innerHTML = '';
        		resetHandledKey();
		}
	}
	else if(document.getElementById('scan_1').innerHTML != '' && document.getElementById('scan_2').innerHTML == '')
		if(barCodeVal.indexOf('\n') != -1||barCodeVal.indexOf('\r') != -1){
			document.getElementById('scan_2').innerHTML = barCodeVal;
        		resetHandledKey();
			
			if(document.getElementById('scan_1').innerHTML != '' && document.getElementById('scan_2').innerHTML != '')
                        	if (document.getElementById('scan_1').innerHTML == document.getElementById('scan_2').innerHTML)
                                	document.getElementById('result').innerHTML = '<font color="green">OK</front>';
                       	 	else
                                	document.getElementById('result').innerHTML = '<font color="red">ERROR</front>';
		}
			
}
//********************* upto here *****************************

</script>
