<?php 
$purchaseorders = $this->getAllpurchaseorders();
$methods = Mage::getSingleton('shipping/config')->getActiveCarriers();
	  $shippingMethods = array();
	  foreach($methods as $_code => $_method)
	 	{
	 		if(!$_title = Mage::getStoreConfig("carriers/$_code/title")){
	            $_title = $_code;
	 		}
	      	$shippingMethods[$_code] = $_title;
	 	}
/*

[0] => Array
        (
            [po_id] => 9
            [vendor_id] => 3
            [shipping_method] => flatrate
            [payment_terms] => 1
            [po_notes] => 
            [date_of_po] => 2015-08-05 00:00:00
            [expected_date] => 1970-01-01 00:00:00
            [order_qty] => 68
            [received_qty] => 0
            [status] => partial
        )

    */?>

<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Purchase Orders") ?></h2>
         <div style="float:right">
            <button class="btn btn-warning" onclick="setLocation('<?php echo $this->getUrl("inventorymanager/adminuser_purchaseorder/new") ?>')" name="addvendors"><?php echo $this->__("create new P.O") ?></button>
        </div>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
                 <?php echo $this->__("All Purchase Orders") ?>
            </div>
            <div class="panel-body">
            	<div class="table-responsive">
            		<table class="table table-striped table-bordered pagination-sm table-hover" id="dataTables-orders">
            			<thead>
            				<tr>
                                <th><?php echo $this->__("ID") ?></th>
                                <th><?php echo $this->__("Vendor Name") ?></th>
                                <th><?php echo $this->__("Shipping Method") ?></th>
                                <th><?php echo $this->__("Ordered Qty") ?></th>
                                <th><?php echo $this->__("Received Qty") ?></th>
                                <th><?php echo $this->__("Date of Purchase order") ?></th>
                                <th><?php echo $this->__("Action") ?></th>
                            </tr>
            			</thead>
            			<tbody>
            				<?php $iCounter = 0; foreach ($purchaseorders as $item){ $iCounter++; ?>
            					<tr class="<?php echo $iCounter%2==0?"odd":"even"; ?>">
            						<td><?php echo $item->getPoId() ?></td>
            						<td><?php echo $this->getVendorname($item->getVendorId()) ?></td>
            						<td><?php echo isset($shippingMethods[$item->getShippingMethod()])?$shippingMethods[$item->getShippingMethod()]:$item->getShippingMethod(); ?></td>
            						<td><?php echo $item->getOrderQty(); ?></td>
            						<td><?php echo $item->getReceivedQty(); ?></td>
            						<td><?php echo date("Y/m/d", strtotime($item->getDateOfPo())) ?></td>
            						<td>
            							<a href="<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder/edit', array('id'=>$item->getPoId())) ?>">
            								<?php echo $this->__("Edit") ?>
            							</a>&nbsp;|&nbsp;
            							<a href="<?php echo $this->getUrl('inventorymanager/adminuser_purchaseorder/delete', array('id'=>$item->getPoId())) ?>">
            								<?php echo $this->__("Delete") ?>
            							</a>
            						</td>
            					</tr>
            				<?php } ?>
            			</tbody>
            		</table>
            	</div>
            </div>
		</div>
	</div>
</div>
<script>
/*jQuery(document).ready(function () {
    jQuery('#dataTables-example').dataTable();
});*/

jQuery(document).ready(function () {
	jQuery('#dataTables-orders').dataTable({
    	"aaSorting": [[0, 'desc']]
	});
});
</script>
