<?php
	$vendorId = $this->getRequest()->getParam('vendor_id');
	$products = $this->getVendorProducts();
	$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
	$currency= Mage::getModel("directory/currency")->load($currency_code);
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Vendors") ?></h2>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
                 <?php echo $this->__("All Vendors") ?>
            </div>
            <div class="panel-body">
            	<div class="table-responsive">
            		<table class="table table-striped table-bordered table-hover" id="dataTables-example">
            			<thead>
            				<tr>
                                <th><?php echo $this->__("ID") ?></th>
                                <th><?php echo $this->__("Name") ?></th>
                                <th><?php echo $this->__("Price") ?></th>
                            </tr>
            			</thead>
            			<tbody>
            				<?php $iCounter = 0; foreach ($products as $_product){ $iCounter++; ?>
            				 <?php $product = Mage::getModel('catalog/product')->load($_product['entity_id']) ?>
            					<tr redirect="<?php echo $this->getUrl("inventorymanager/adminuser_vendor/productinfo" , array('product_id'=>$_product->getId(), 'vendor_id'=>$vendorId)) ?>" class="clickable-row <?php echo $iCounter%2==0?"odd":"even"; ?>">
            						<td><?php echo $product->getId() ?></td>
            						<td><?php echo $product->getName() ?></td>
            						<td><?php echo  $currency->formatPrecision($_product->getData('cost'),2); ?></td>
            					</tr>
            				<?php } ?>
            			</tbody>
            		</table>
            	</div>
            </div>
		</div>
	</div>
</div>
<script>
jQuery(document).ready(function () {
    var table = jQuery('#dataTables-example').dataTable();
    
    jQuery('#dataTables-example tbody').on('click', 'tr', function () {
	    var url = jQuery(this).attr('redirect');
        location.href = url;
    } );
    
});
</script>