<?php
	$currentProduct = $this->getProduct();
?>
<li>
	<div class="product-content p-name"><?php echo $currentProduct->getName() ?></div>
	<div class="product-content p-qty">
		<input type="text" value="1" name="qty[<?php echo $currentProduct->getId() ?>]" class="input-text" onchange="countTotal(this)" />
	</div>
	<div class="product-content p-cost"><?php echo $currentProduct->getPrice()?$currentProduct->getPrice():0; ?>
		<input type="text" value="0.0000" name="product_value[<?php echo $currentProduct->getId() ?>]" class="input-text" onchange="countTotal(this)" />
	</div>
	<div id="total" class="product-content p-total p-input">
		0.0000
	</div>
	<div class="product-content p-remove"> <a onclick="removeProduct(this)" >X</a> </div>
	<div class="clear-float"></div>
</li>