<?php
	$currentProduct = $this->getProduct();
	$vendorProduct = $this->getVendorProduct();
	$cost = $currentProduct->getPrice();
	if($vendorProduct && $vendorProduct->getId()){
		$cost = $vendorProduct->getCost();
	}
?>
<li>
	<div class="product-content p-name">
		<?php echo $currentProduct->getName() ?>
		<input type="hidden" name="po_product[]" value="<?php echo $currentProduct->getId() ?>" />
	</div>
	<div class="product-content p-qty">
		<input type="text" value="1" name="qty[<?php echo $currentProduct->getId() ?>]" class="input-text" onchange="countTotal(this)" />
	</div>
	<div class="product-content p-cost"><?php echo $cost ?>
		<input type="text" value="<?php echo $cost ?>" name="product_value[<?php echo $currentProduct->getId() ?>]" class="input-text" onchange="countTotal(this)" />
	</div>
	<div id="total" class="product-content p-total p-input">
		<?php echo $cost ?>
	</div>
	<div class="product-content p-remove"> <a onclick="removeProduct(this)" >X</a> </div>
	<div class="clear-float"></div>
</li>