<?php $comments = $this->getPurchaseOrderComments(); if($comments && $comments->count() > 0){ ?>
	<?php foreach ($comments as $comment){ ?>
		<li>
			<strong><?php echo date("M d, Y h:i:s a",strtotime($comment->getCreatedTime())); ?></strong>
			<a class="orderspro-delete" title="Delete" onclick="deleteComment(<?php echo $comment->getId() ?>); return false;" href="">x</a>
			<br/>
			<?php echo $comment->getComment(); ?>
		</li>
	<?php } ?>
<?php } ?>