<?php
	$_product = $this->getCurrentProduct();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $_product->getName(); ?></h2>
		<h5><?php echo $_product->getSku(); ?></h5>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<?php echo $this->__("Mofify Product Infomation") ?>	
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<form>
							<div class="form-group">
								<label><?php echo $this->__("Description") ?></label>
								<textarea name="description" class="required-entry form-control"></textarea>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Cost") ?></label>
								<input type="text" class="required-entry form-control" name="cost" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Length") ?></label>
								<input type="text" class="required-entry form-control" name="length" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Width") ?></label>
								<input type="text" class="required-entry form-control" name="width" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Hight") ?></label>
								<input type="text" class="required-entry form-control" name="height" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Fun Specs") ?></label>
								<input type="text" class="required-entry form-control" name="fun_specs" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Material") ?></label>
								<select class="required-entry form-control" name="material">
									<option value="3"><?php echo $this->__("30") ?></option>
									<option value="4"><?php echo $this->__("40") ?></option>
									<option value="5"><?php echo $this->__("50") ?></option>
								</select>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Lighting") ?></label>
								<select class="required-entry form-control" name="material">
									<option value="1"><?php echo $this->__("Led 1w") ?></option>
									<option value="2"><?php echo $this->__("Led 2w") ?></option>
									<option value="3"><?php echo $this->__("Led 3w") ?></option>
								</select>
							</div>
							<button class="btn btn-default" type="submit"><?php echo $this->__("Save") ?></button>
							<button class="btn btn-primary" type="reset"><?php echo $this->__("Reset") ?></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>