<?php
	$product = $this->getProductObject();
	$revisionObject = $this->getCurrentRevision();
	$productInfoObject = $this->getProductInfoObject();
	$fieldTitles = Mage::helper('inventorymanager')->getProductInfoFieldTitles();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Revision") ?></h2>
		<h5><?php echo $product->getName() ?></h5>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<?php echo $this->__("Differences") ?>
				<a href="<?php echo $this->getUrl("inventorymanager/vendor_product/loadRevision", array("revision_id"=>$revisionObject->getId())) ?>" class="load-revision-link btn btn-warning btn-xs"><?php echo $this->__("Load this Revision") ?></a>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<td>#</td>
								<td><?php echo $this->__("Active Version") ?></td>
								<td><?php echo $this->__("Revision") ?></td>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->getDifferences() as $key => $difference){
								if(isset($fieldTitles[$key])){?>
									<tr>
										<td><?php echo $fieldTitles[$key] ?></td>
										<td><?php echo $productInfoObject->getData($key) ?></td>
										<td><?php echo $revisionObject->getData($key) ?></td>
									</tr>
								<?php }
							} ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>