<?php
	$revisionList = $this->getRevisionList();
	if($revisionList->count() && $revisionList->count() > 0){
?>
<div class="panel panel-default">
	<div class="panel-heading"  >
		<?php echo $this->__("Revisions") ?>	
	</div>
	<div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<td>#</td>
							<td><?php echo $this->__("Date") ?></td>
						</tr>
					</thead>
					<tbody>
						<?php $iCounter=0; foreach ($revisionList as $revision){ ?>
							<tr>
								<td><?php echo ++$iCounter; ?></td>
								<td>
									<a href="<?php echo $this->getUrl("inventorymanager/vendor_product/showrevision", array('revision_id'=>$revision->getId())) ?>">
										<?php echo $revision->getCreatedTime(); ?>
									</a>
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<?php } ?>