<div class="panel panel-default">
	<div class="panel-heading" id="drow-tab" >
		<?php echo $this->__("Drawings") ?>	
	</div>
	<div class="drow-tab-content" id="drow-tab-content">
		<div class="panel-body">
			<?php $files = $this->getFiles(); ?>
			<?php if(sizeof($files) > 0) { ?>
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<td>#</td>
							<td><?php echo $this->__("Files") ?></td>
							<td><?php echo $this->__("Action") ?></td>
						</tr>
					</thead>
					<tbody>
						<?php $iCounter = 0; foreach ($files as $file){ ?>
							<tr>
								<td><?php echo ++$iCounter; ?></td>
								<td><?php echo $file; ?></td>
								<td><a href="<?php echo $this->getUrl("inventorymanager/vendor_product/download", array('file'=>$file)) ?>"><?php echo $this->__("Download") ?></a></td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
			<?php } ?>
			<form id="file_upload_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl("inventorymanager/vendor_product/upload") ?>">
				<div class="btn-fileupload">
					<input name="upl" class="btn-default " id="upl" size="27" type="file" />
					<div class="validation-advice" id="advice-required-entry-upl"></div>
				</div>
				<button type="submit" name="action" class="btn btn-default"><?php echo $this->__("Upload") ?></button>
				<iframe id="upload_target" name="upload_target" src="" style="width:0;height:0;border:0px solid #fff;"></iframe>
			</form>
			<div id="message">
			</div>
		</div>
	</div>
</div>
<script>
function init() {
	document.getElementById('file_upload_form').onsubmit=function() {
		if($('upl').value != ""){
			document.getElementById('file_upload_form').target = 'upload_target'; //'upload_target' is the name of the iframe
			displayfile($('upl').value);
			//$('upl').value = "";
		}else{
			$('advice-required-entry-upl').innerHTML = "<?php echo $this->__("Please select a file") ?>";
			return false;
		}
	}
	$('uploaded_file').value = '<?php echo implode(",", $files); ?>,';
}

function displayfile(file){
	$('message').innerHTML += '<div class="">'+ file +'</div>';
	$('uploaded_file').value += file + ",";
}
window.onload=init;
</script>