<?php
	$labelObject = $this->getLabelObject();
	$catalogProduct = $this->gerMainProduct();
	$_helper = $this->helper('catalog/output');
	$labelComments = $this->getComments();
	$status = Mage::helper('inventorymanager')->getOrderedProductStatusArray();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Product Information") ?></h2>
		<h5><?php echo $this->__("Update Product Information") ?></h5>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $catalogProduct->getName() ?></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<form action="<?php echo $this->getUrl("inventorymanager/label/editpost") ?>" method="POST" id="edit_productlabel">
							<input type="hidden" value="<?php echo $labelObject->getId() ?>" name="label_id" />
							<div class="form-group">
								<label><?php echo $this->__("Serial Key") ?></label>
								<p class="form-control-static"><?php echo $labelObject->getSerial(); ?></p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Height") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodHeightInches(), 'hood_height_inches') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Width") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodWidthInches(), 'hood_width_inches') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Depth") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodDepth(), 'hood_depth') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Status") ?></label>
								<div class="form-control-static" >
									<div class="btn-group show-dropbox">
										<div class="form-group input-group show-dropbox" id="status-text-div" style="float:left; margin-right:0px;">
							  				<input type="text" class="form-control" onkeyup="statusText(this.value)" name="status" id="new_status" value="<?php echo $labelObject->getStatus(); ?>" />
							  			</div>
									  	<button type="button" class="btn btn-primary dropdown-toggle" id="openbox-button" style="z-index:999"><span class="caret"></span></button>
									  	<ul class="dropdown-menu" id="dropdown-box">
									  		<li class="add-status-li"><a href="javascript:void(0);" id="new_status_link" ><?php echo $this->__("Add New") ?></a></li>
									  		<?php foreach ($status as $key => $statusLabel) { ?>
									  			<li><a class="status-options" href="javascript:void(0);"><?php echo $statusLabel ?></a></li>
									  		<?php } ?>
									  	</ul>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Comments") ?></label>
							</dir>
							
								<?php if($labelComments && $labelComments->count() > 0){ ?>
									<table class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<td><?php echo $this->__("Date") ?></td>
												<td><?php echo $this->__("Comment") ?></td>
											</tr>
										</thead>
										<?php foreach ($labelComments as $comment){ ?>
											<tr>
												<td><?php echo date("Y-m-d", strtotime($comment->getCreatedTime())); ?></td>
												<td><?php echo $comment->getComment() ?></td>
											</tr>
										<?php } ?>
									</table>
								<?php } ?>
							
							<div class="form-group">
								<label><?php echo $this->__("Comment") ?></label>
								<textarea class="form-control" rows="2" name="comment"></textarea>
							</div>
							<div class="form-group">
								<a class="btn btn-warning" onclick="if(dataForm.validator && dataForm.validator.validate()){ dataForm.form.submit(); }" href="#"><?php echo $this->__("Update") ?></a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	var dataForm = new VarienForm('edit_productlabel', false);
</script>
<script>

	var statuses = [];
	<?php foreach ($status as $statusLabel) { ?>
		statuses.push("<?php echo $statusLabel ?>");
	<?php } ?>

	function statusText(val){
		$('new_status_link').innerHTML = '<?php echo $this->__("Add") ?> ' + val;
	}
	
	$$('a.status-options').each(function(e){
		e.observe('click', function(){
			$('new_status').value = e.innerHTML;
			$('dropdown-box').toggleClassName('show-dropbox');
		});
	});
	
	$('status-text-div').observe('click', function(){
		$('dropdown-box').addClassName('show-dropbox');
	});
	
	$('openbox-button').observe('click', function(){
		$('dropdown-box').toggleClassName('show-dropbox');
	});
	
	$('new_status_link').observe('click', function(){
		var status = $('new_status').value;
		var currentIndex = statuses.indexOf(status);
		if(currentIndex>=0){
			return;
		}
		new Ajax.Request('<?php echo $this->getUrl('inventorymanager/label/addnewstatus') ?>', {
  			method:'post',
  			parameters: {status: status},
  			onSuccess: function(transport) {
    			var response = transport.responseText;
    			if(response != ''){
    				alert(response);
    			}else{
    				$('dropdown-box').innerHTML = $('dropdown-box').innerHTML + '<li><a class="status-options" href="javascript:void(0);">'+status+'</a></li>';
    				$$('a.status-options').each(function(e){
						e.observe('click', function(){
							$('new_status').value = e.innerHTML;
							$('dropdown-box').toggleClassName('show-dropbox');
						});
					});
					$('dropdown-box').toggleClassName('show-dropbox');
    			}
  			},
  			onFailure: function() { alert('Something went wrong...');}
		});
	});
</script>