<?php
	$labelObject = $this->getLabelObject();
	$catalogProduct = $this->gerMainProduct();
	$_helper = $this->helper('catalog/output');
	$labelComments = $this->getComments();
	$status = Mage::helper('inventorymanager')->getOrderedProductStatusArray();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Product Information") ?></h2>
		<h5><?php echo $this->__("Update Product Information") ?></h5>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $catalogProduct->getName() ?></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<form action="<?php echo $this->getUrl("inventorymanager/label/editpost") ?>" method="POST" id="edit_productlabel">
							<input type="hidden" value="<?php echo $labelObject->getId() ?>" name="label_id" />
							<div class="form-group">
								<label><?php echo $this->__("Serial Key") ?></label>
								<p class="form-control-static"><?php echo $labelObject->getSerial(); ?></p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Height") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodHeightInches(), 'hood_height_inches') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Width") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodWidthInches(), 'hood_width_inches') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Depth") ?></label>
								<p class="form-control-static">
									<?php echo $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodDepth(), 'hood_depth') ?>
								</p>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Status") ?></label>
								<div class="form-control-static" >
									<div class="btn-group show-dropbox">
										<div class="form-group input-group" style="float:left; margin-right:0px;">
							  				<input type="text" class="form-control" name="status" id="new_status" value="<?php echo isset($status[$labelObject->getStatus()])?$status[$labelObject->getStatus()]:""; ?>" />
							  			</div>
									  	<button data-toggle="dropdown" class="btn btn-primary dropdown-toggle" style="z-index:999"><span class="caret"></span></button>
									  	<ul class="dropdown-menu">
									  		<?php foreach ($status as $key => $statusLabel) { ?>
									  			<li><a onclick="$('new_status').value = '<?php echo $statusLabel ?>';" href="javascript:void(0);"><?php echo $statusLabel ?></a></li>
									  		<?php } ?>
									  	</ul>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Comments") ?></label>
							</dir>
							
								<?php if($labelComments && $labelComments->count() > 0){ ?>
									<table class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<td><?php echo $this->__("Date") ?></td>
												<td><?php echo $this->__("Comment") ?></td>
											</tr>
										</thead>
										<?php foreach ($labelComments as $comment){ ?>
											<tr>
												<td><?php echo date("Y-m-d", strtotime($comment->getCreatedTime())); ?></td>
												<td><?php echo $comment->getComment() ?></td>
											</tr>
										<?php } ?>
									</table>
								<?php } ?>
							
							<div class="form-group">
								<label><?php echo $this->__("Comment") ?></label>
								<textarea class="form-control" rows="2" name="comment"></textarea>
							</div>
							<div class="form-group">
								<a class="btn btn-warning" onclick="if(dataForm.validator && dataForm.validator.validate()){ dataForm.form.submit(); }" href="#"><?php echo $this->__("Update") ?></a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	var dataForm = new VarienForm('edit_productlabel', false);
</script>
<script>
	function openSelect(){
		$('select_status').toggle();
	}
</script>