<?php $historyCollection = $this->getHistory() ?>
<?php if($historyCollection && $historyCollection->count() > 0){ ?>
<?php $serialObject = $this->getSerial(); ?>
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Label History") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
						<table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example">
							<thead>
								<tr char="row">
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 353px;" aria-label="Browser: activate to sort column ascending">
										<?php echo $this->__("Date") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Location") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Current Location") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Status") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Current Status") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Agent") ?>
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$icounter = 0;
								foreach ($historyCollection as $history){
								?>
									<tr class="<?php echo $icounter%2==0?"even":""; ?> gradeA clickable-row">
										<td><?php echo date("Y-m-d", strtotime($history->getCreatedTime())) ?></td>
										<td><?php echo $history->getLocation() ?></td>
										<td><?php echo $serialObject->getLocation() ?></td>
										<td><?php echo $history->getStatus() ?></td>
										<td><?php echo $serialObject->getStatus() ?></td>
										<td><?php echo $this->getUser($history->getUserId()); ?></td>
									</tr> 
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
<?php } ?>