<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Send a product") ?></h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Enter Information") ?></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<?php echo $this->getMessagesBlock()->toHtml() ?>
						<form action="<?php echo $this->getUrl("inventorymanager/adminuser_serial/findpost") ?>" method="POST" id="find_label">
							<div class="form-group">
								<label><?php echo $this->__("Enter Order Number") ?></label>
								<input type="text" class="form-control required-entry" name="order_number" />
							</div>
							<div class="form-group">
								<label><?php echo $this->__("Enter Serial Key") ?></label>
								<input type="text" class="form-control required-entry" name="serial_key" />
							</div>
							<div class="form-group">
								<a class="btn btn-warning" onclick="if(dataForm.validator && dataForm.validator.validate()){ dataForm.form.submit(); }" href="#"><?php echo $this->__("Submit") ?></a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	var dataForm = new VarienForm('find_label', false);
</script>