<?php $products = $this->getProducts(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div>
	<ul>
		<?php foreach ($products as $product){ ?>
		<?php
			$orderProduct = Mage::getModel('inventorymanager/product')->load($product->getProductId());
			$catalogProduct = Mage::getModel('catalog/product')->load($orderProduct->getMainProductId());
			$productInfoObject = $this->getProductrInfoObject($orderProduct->getMainProductId());
			$imageHtml = "";
			if($productInfoObject && $productInfoObject->getMainImage() != ""){
				$imageHtml =  '<img src="'.$this->helper("inventorymanager")->resizeImage($productInfoObject->getMainImage(), 100, 100, "productdetail/").'" />';
			}
			$height = $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodHeightInches(), 'hood_height_inches');
			$width =  $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodWidthInches(), 'hood_width_inches');
			$depth = $_helper->productAttribute($catalogProduct, $catalogProduct->getHoodDepth(), 'hood_depth');
			
			if($productInfoObject && $productInfoObject->getHeight() && $productInfoObject->getHeight() > 0){
				$height = $productInfoObject->getHeight();
			}
			if($productInfoObject &&  $productInfoObject->getWidth() && $productInfoObject->getWidth() > 0){
				$width = $productInfoObject->getWidth();
			}
			if($productInfoObject && $productInfoObject->getLength() && $productInfoObject->getLength() > 0){
				$depth = $productInfoObject->getLength();
			}
		?>
			<li style="border:1px solid #ccc;">
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td>
							<img src="<?php echo str_replace(array("index.php","index.php/"), "", Mage::getBaseUrl())	."barcode.php?text=".$product->getSerial()."&size=32"; ?>" />
							<span style="float:right"><?php echo $imageHtml ?></span>
						</td>
					</tr>
					<tr>
						<td><?php echo $product->getSerial() ?></td>
					</tr>
				</table>
				<table border="1" cellpadding="5" width="100%">
					<?php /* <tr>
						<td><?php echo $this->__("Serial") ?></td>
						<td><?php echo $product->getSerial() ?></td>
					</tr> */ ?>
					<tr>
						<td><?php echo $this->__("Product") ?></td>
						<td><?php echo $catalogProduct->getName() ?></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Weight") ?></td>
						<td><?php echo $catalogProduct->getWeight() ?></td>
					</tr>
				</table>
				<table border="1" cellpadding="5" width="100%">
					<tr>
						<td><?php echo $this->__("Height") ?></td>
						<td><?php echo $this->__("Width") ?></td>
						<td><?php echo $this->__("Depth") ?></td>
					</tr>
					<tr>
						<td><?php echo $height ?></td>
						<td><?php echo $width ?></td>
						<td><?php echo $depth ?></td>
					</tr>
				</table>
			</li>
			<li style="list-style: none"><br/><br/><br/></li>
		<?php } ?>
	</ul>
</div>