<?php $vendorProducts = $this->getVendorProducts() ?>
<?php $vender = $this->getCurrentVendor(); ?>


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Vendor Products") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
						<table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example">
							<thead>
								<tr char="row">
									<th class="sorting_asc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 69px;" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending">
										<?php echo $this->__("ID") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 353px;" aria-label="Browser: activate to sort column ascending">
										<?php echo $this->__("Name") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("SKU") ?>
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$icounter = 0;
								foreach ($vendorProducts as $productData){
								$product = Mage::getModel('catalog/product')->load($productData['entity_id']) ?>
									<tr id="products_tr_<?php echo $product->getId() ?>" class="<?php echo $icounter%2==0?"even":""; ?> gradeA">
										<td class="sorting_1"><a href="<?php echo $this->getUrl("inventorymanager/vendor_product/edit", array('id'=>$product->getId())) ?>"><?php echo $product->getId() ?></a></td>
										<td><a href="<?php echo $this->getUrl("inventorymanager/vendor_product/edit", array('id'=>$product->getId())) ?>"><?php echo $product->getName() ?></a></td>
										<td><a href="<?php echo $this->getUrl("inventorymanager/vendor_product/edit", array('id'=>$product->getId())) ?>"><?php echo $product->getSku() ?></a></td>
									</tr>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
jQuery(document).ready(function () {
    jQuery('#dataTables-example').dataTable();
});
</script>