<div>
	<div>
		<?php echo $this->getMessagesBlock()->toHtml() ?>
		<form action="<?php echo $this->getUrl('inventorymanager/vendor/loginpost') ?>" id="vendor-form" method="POST">
			<h2><?php echo $this->__("Vendor Login") ?></h2>
			<table class="form-list">
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>
						<label><?php echo $this->__("Username")  ?>&nbsp;: &nbsp;</label>
					</td>
					<td>
						<input type="text" class="required-entry input-text" name="username" />
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td>
						<label><?php echo $this->__("Password")  ?>&nbsp;: &nbsp;</label>
					</td>
					<td>
						<input type="password" class="required-entry input-text" name="password" />
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="2">
						<button class="button" type="submit">
							<span><span><span><?php echo $this->__("Login") ?></span> </span> </span>
						</button>
					</td>
				</tr>
			</table>
		</form>
		<script>
			var dataForm = new VarienForm('vendor-form', true);
		</script>
	</div>
</div>