<?php
	$catalogProduct = $this->getCatalogProduct();
	$orderProducts = $this->getVendorProduct();
	$locations = $this->helper('inventorymanager')->getAgentLocations();
?>
	<table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example">
		<thead>
			<tr char="row">
				
				<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 353px;" aria-label="Browser: activate to sort column ascending">
					<?php echo $this->__("Serial") ?>
				</th>
				<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
					<?php echo $this->__("Location") ?>
				</th>
				<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
					<?php echo $this->__("Status") ?>
				</th>
			</tr>
		</thead>
		<tbody id="serials_list">
			<?php if($serials = $this->getSerialsByCatalogProduct()){ ?>
				<?php foreach ($serials as $serialObject){ ?>
					<tr class="<?php echo $icounter%2==0?"even":""; ?> gradeA">
						<td><?php echo $serialObject->getSerial() ?></td>
						<td>
							<div class="form-control-static" >
								<div class="btn-group show-dropbox">
									<div class="form-group input-group show-dropbox" style="float:left; margin-right:0px; width:60%">
						  				<input type="text" class="form-control new_location" name="location" id="" value="<?php echo $serialObject->getLocation(); ?>" />
						  			</div>
								  	<button type="button" class="btn btn-primary dropdown-toggle openbox-button-location" id="" style="z-index:999"><span class="caret"></span></button>
								  	<ul class="dropdown-menu" id="dropdown-box-location">
								  		<li class="add-location-li new_location_link"><a href="javascript:void(0);" class="add-new-status-link" id="" ><?php echo $this->__("Add New") ?></a></li>
								  		<?php foreach ($locations as $key => $locationLabel) { ?>
								  			<li><span class="remove-location-link">x</span><a class="location-options" href="javascript:void(0);"><?php echo $locationLabel ?></a></li>
								  		<?php } ?>
								  	</ul>
								</div>
							</div>	
						</td>
						<td><?php echo $serialObject->getStatus(); ?></td>
					</tr>
				<?php } ?>
			<?php } ?>
		</tbody>
	</table>