<?php
	$catalogProduct = $this->getCatalogProduct();
	$orderProducts = $this->getVendorProduct();
?>
<div class="row">
	<div class="col-md-12">
		<h2><?php echo $catalogProduct->getName() ?></h2>
		<h5><?php echo $catalogProduct->getSku() ?></h5>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Product Serials") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
						<table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example">
							<thead>
								<tr char="row">
									
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 353px;" aria-label="Browser: activate to sort column ascending">
										<?php echo $this->__("Serial") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Location") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("Status") ?>
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								/*$icounter = 0;
								foreach ($orderProducts as $orderProductObject){
									$serials = $this->getSerials($orderProductObject->getId());
									foreach ($serials as $serialObject){?>
										<tr class="<?php echo $icounter%2==0?"even":""; ?> gradeA">
											<td><?php echo $serialObject->getSerial() ?></td>
											<td><?php echo $serialObject->getLocation() ?></td>
											<td><?php echo $serialObject->getStatus(); ?></td>
										</tr>
									<?php }
								}*/ ?>
								<?php if($serials = $this->getSerialsByCatalogProduct()){ ?>
									<?php foreach ($serials as $serialObject){ ?>
										<tr class="<?php echo $icounter%2==0?"even":""; ?> gradeA">
											<td><?php echo $serialObject->getSerial() ?></td>
											<td><?php echo $serialObject->getLocation() ?></td>
											<td><?php echo $serialObject->getStatus(); ?></td>
										</tr>
									<?php } ?>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
jQuery(document).ready(function () {
    jQuery('#dataTables-example').dataTable();
    
});

jQuery(".clickable-row").click(function() {
    window.document.location = jQuery(this).data("href");
});
</script>