<?php $catalogProducts = $this->getProducts() ?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Products' Stock") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
						<table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example">
							<thead>
								<tr char="row">									
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 353px;" aria-label="Browser: activate to sort column ascending">
										<?php echo $this->__("Name") ?>
									</th>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("SKU") ?>
									</th>
									<?php /* 
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("STOCK") ?>
									</th> */ ?>
									<th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" style="width: 142px;" aria-label="Engine version: activate to sort column ascending">
										<?php echo $this->__("SERIAL COUNT") ?>
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$icounter = 0;
								foreach ($catalogProducts as $productData){
									$product = Mage::getModel('catalog/product')->load($productData['entity_id']);
									
									$serialCount = $this->getSerialCount($product);
									
									$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product);
									
									if($serialCount > 0){
									?>
										<tr data-href="<?php echo $this->getUrl("inventorymanager/adminuser_product/serialgrid", array('product_id'=>$product->getId())) ?>" class="<?php echo $icounter%2==0?"even":""; ?> gradeA clickable-row">
											<td><?php echo $product->getName() ?></td>
											<td><?php echo $product->getSku() ?></td>
											<?php /* <td><?php echo $stock?(int)$stock->getQty():""; ?></td> */ ?>
											<td><?php echo $serialCount ?></td>
										</tr>
									<?php } ?>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
jQuery(document).ready(function () {
    jQuery('#dataTables-example').dataTable();
    
});

jQuery(".clickable-row").click(function() {
    window.document.location = jQuery(this).data("href");
});
</script>