<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Fedex History") ?></h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("History Information") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
							<tr>
								<td><?php echo "#"; ?></td>
								<td><?php echo $this->__("Career"); ?></td>
								<td><?php echo $this->__("Tracking Number"); ?></td>
								<td><?php echo $this->__("Serivce"); ?></td>
								<td><?php echo $this->__("Weight"); ?></td>
								<td><?php echo $this->__("Quoted Value"); ?></td>
								<td><?php echo $this->__("Date"); ?></td>
							</tr>
						</thead>
						<?php $historyCollection = $this->getHistory(); ?>
						<?php if($historyCollection && $historyCollection->count()){ ?>
							<tbody>
							<?php foreach ($historyCollection as $historyObject){ ?>
								<tr>
									<td><?php echo $historyObject->getId() 	?></td>
									<td><?php echo $historyObject->getTransactionDetail() ?></td>
									<td><?php echo $historyObject->getCareercode() ?></td>
									<td><?php echo $historyObject->getServiceType() ?></td>
									<td><?php echo $historyObject->getWeight() ?></td>
									<td><?php echo $historyObject->getQuotedValue() ?></td>
									<td><?php echo $historyObject->getShippingDate() ?></td>
								</tr>
							<?php } ?>
							</tbody>
						<?php } ?>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>