<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Shipmanager - Ship")  ?></h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Fedex Ship information") ?></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label><?php echo $this->__("Order Number") ?></label>
							<input type="text" class="form-control" name="order_id" id="order_id" placeholder="<?php echo $this->__("Enter Real Order Id") ?>" />
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<h3><?php echo $this->__("Shipper Information") ?></h3>
						<div class="form-group">
							<label><?php echo $this->__("Company") ?></label>
							<input type="text" class="form-control" name="company" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Phone") ?></label>
							<input type="text" class="form-control" name="phone" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Contact Name") ?></label>
							<input type="text" class="form-control" name="contact_name" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Email Address") ?></label>
							<input type="text" class="form-control" name="email" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Country") ?></label>
							<?php $_countries = Mage::getResourceModel('directory/country_collection')->loadByStore()->toOptionArray(false) ?>
							<?php if (count($_countries) > 0): ?>
							    <select name="billing[country_id]" id="billing:country_id" class="form-control validate-select">
							        <option value="">Please choose a country...</option>
							        <?php foreach($_countries as $_country): ?>
							            <option value="<?php echo $_country['value'] ?>">
							                <?php echo $_country['label'] ?>
							            </option>
							        <?php endforeach; ?>
							    </select>
							<?php endif; ?>
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Address") ?></label>
							<input type="text" class="form-control" name="address" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Address 2") ?></label>
							<input type="text" class="form-control" name="address2" />
						</div>
						<div class="form-group">
							<div class="checkbox">
								<label>
									<input type="checkbox" value="1" name="residential_address" />
									<?php echo $this->__("Residential Address") ?>
 								</label>
							</div>
						</div>
						<div class="form-group">
							<label><?php echo $this->__("City") ?></label>
							<input type="text" class="form-control" name="city" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Postal Code") ?></label>
							<input type="text" class="form-control" name="postalcode" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("State") ?></label>
							<input type="text" class="form-control" name="state" />
						</div>
					</div>
					<div class="col-md-6">
						<h3><?php echo $this->__("Receiver Address") ?></h3>
						<div class="form-group">
							<label><?php echo $this->__("Company") ?></label>
							<input type="text" class="form-control" name="company" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Phone") ?></label>
							<input type="text" class="form-control" name="phone" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Contact Name") ?></label>
							<input type="text" class="form-control" name="contact_name" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Email Address") ?></label>
							<input type="text" class="form-control" name="email" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Country") ?></label>
							<?php $_countries = Mage::getResourceModel('directory/country_collection')->loadByStore()->toOptionArray(false) ?>
							<?php if (count($_countries) > 0): ?>
							    <select name="billing[country_id]" id="billing:country_id" class="form-control validate-select">
							        <option value="">Please choose a country...</option>
							        <?php foreach($_countries as $_country): ?>
							            <option value="<?php echo $_country['value'] ?>">
							                <?php echo $_country['label'] ?>
							            </option>
							        <?php endforeach; ?>
							    </select>
							<?php endif; ?>
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Address") ?></label>
							<input type="text" class="form-control" name="address" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Address 2") ?></label>
							<input type="text" class="form-control" name="address2" />
						</div>
						<div class="form-group">
							<div class="checkbox">
								<label>
									<input type="checkbox" value="1" name="residential_address" />
									<?php echo $this->__("Residential Address") ?>
 								</label>
							</div>
						</div>
						<div class="form-group">
							<label><?php echo $this->__("City") ?></label>
							<input type="text" class="form-control" name="city" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("Postal Code") ?></label>
							<input type="text" class="form-control" name="postalcode" />
						</div>
						<div class="form-group">
							<label><?php echo $this->__("State") ?></label>
							<input type="text" class="form-control" name="state" />
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h3><?php echo $this->__("Package Information") ?></h3>
						<div class="row">
							<div class="col-md-6">
							
								<div class="form-group">
									<label><?php echo $this->__("Shipping Date") ?></label>
									<input type="text" class="form-control" name="Shipping Date" />
								</div>
								<div class="form-group">
									<label><?php echo $this->__("Service Type") ?></label>
									<select name="service_type" class="form-control">
										<option value="FEDEX_FREIGHT_ECONOMY">Fedex Fright Economy</option>
										<option value="FEDEX_FREIGHT_PRIORITY">Fedex Fright Priority</option>
									</select>
								</div>
								<div class="form-group">
									<label><?php echo $this->__("Package Type") ?></label>
									<select name="package_type" class="form-control">
										<option value="FEDEX_10KG_BOX">Fedex 10KG Box</option>
										<option value="FEDEX_25KG_BOX">Fedex 25KG Box</option>
										<option value="FEDEX_SMALL_BOX">Fedex Small Box</option>
										<option value="FEDEX_MEDIUM_BOX">Fedex Medium Box</option>
										<option value="FEDEX_LARGE_BOX">Fedex Large Box</option>
										<option value="FEDEX_EXTRA_LARGE_BOX">Fedex Extra Large Box</option>
										<option value="YOUR_PACKAGING">Your Packaging</option>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<div class="table-responsive table-bordered">
									<table class="table">
										<thead>
											<tr>
												<th width="50%"><?php echo $this->__("Serial") ?></th>
												<th><?php echo $this->__("Weight") ?></th>
												<th><?php echo $this->__("Length") ?></th>
												<th><?php echo $this->__("Width") ?></th>
												<th><?php echo $this->__("Height") ?></th>
												<th><?php echo $this->__("") ?></th>
											</tr>
										</thead>
										<tbody id="serial_package_info">
											<tr>
												<td><input type="text" class="form-control"  name="serial_key[1]" /></td>
												<td><input type="text" class="form-control"  name="weight[1]" /></td>
												<td><input type="text" class="form-control"  name="length[1]" /></td>
												<td><input type="text" class="form-control" name="width[1]" /></td>
												<td><input type="text" class="form-control" name="height[1]" /></td>
												<td><a class="btn btn-info" href="javascript:void(0)" onclick="addSerialRow()"><?php echo $this->__("Add New") ?></a></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	var serialIncrement = 1;
	function addSerialRow(){
		serialIncrement++;
		var newTR = '<tr>';
		newTR += '<td><input type="text" class="form-control" name="serial_key['+serialIncrement+']" /></td>';
			newTR += '<td><input type="text" class="form-control" name="weight['+serialIncrement+']" /></td>';
			newTR += '<td><input type="text" class="form-control" name="length['+serialIncrement+']" /></td>';
			newTR += '<td><input type="text" class="form-control" name="width['+serialIncrement+']" /></td>';
			newTR += '<td><input type="text" class="form-control" name="height['+serialIncrement+']" /></td>';
			newTR += '<td><a class="btn btn-danger" href="javascript:void(0)" onclick="removeThisRow(this)"><?php echo $this->__("Remove") ?></a></td>';
		newTR += '</tr>';
		jQuery('#serial_package_info').append(newTR);
	}
	
	function removeThisRow(element){
		element.up('tr').remove();
	}
</script>