<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->__("Orders waiting for Shipment") ?></h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><?php echo $this->__("Orders Information") ?></div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
							<tr>
								<td><?php echo $this->__("Order #"); ?></td>
								<td><?php echo $this->__("Purchased From (Store)"); ?></td>
								<td><?php echo $this->__("Purchased On"); ?></td>
								<td><?php echo $this->__("Bill to name"); ?></td>
								<?php /* <td><?php echo $this->__("Bill to Company"); ?></td>
								<td><?php echo $this->__("Products"); ?></td>
								<td><?php echo $this->__("Ship to Name"); ?></td>
								<td><?php echo $this->__("G.T.(Base)"); ?></td>
								<td><?php echo $this->__("G.T.(Purchased)"); ?></td>
								*/?>
								<td><?php echo $this->__("Source"); ?></td>
							</tr>
						</thead>
						<tbody>
						<?php $historyCollection = $this->getOrders();?>
						<?php if($historyCollection && count($historyCollection)>0){ ?>
							<?php foreach ($historyCollection as $historyObject){ ?>
								<tr>
									<td><?php echo $historyObject->getIncrementId() 	?></td>
									<td><?php echo $this->getStorename($historyObject->getStoreId()) ?></td>
									<td><?php echo $historyObject->getCreatedAt() ?></td>
									<td><?php echo $historyObject->getCustomerName() ?></td>
									<?php /*<td><?php echo $historyObject->getCustomerCompany() ?></td>
									<td><?php echo $historyObject->getQuotedValue() ?></td>
									<td><?php echo $historyObject->getShippingDate() ?></td>
									<td><a href="<?php echo $this->getUrl('inventorymanager/adminuser_shipmanager/download', array('filename'=>$serialId.'-BillOfLading.pdf', 'area'=>'bol')) ?>"> <?php echo $serialId.'-BillOfLading.pdf'; ?> </td>
									<td><a href="<?php echo $this->getUrl('inventorymanager/adminuser_shipmanager/download', array('filename'=>$serialId.'-ShippingLabel.pdf', 'area'=>'label')) ?>"> <?php echo $serialId.'-ShippingLabel.pdf'; ?> </td>
									*/?>
									<td><?php echo $this->__("Magento");?></td>
								</tr>
							<?php }	 ?>
						<?php }	 ?>
						<?php $historyOscommerceCollection = $this->getOscommerceOrders(); ?>
						<?php if(!empty($historyOscommerceCollection)){?>
							<?php foreach ($historyOscommerceCollection as $historyObject){ ?>
								<tr>
									<td><?php echo $historyObject['orders_id'] ?></td>
									<td><?php echo "-"; ?></td>
									<td><?php echo $historyObject['date_purchased'] ?></td>
									<td><?php echo $historyObject['customers_name'] ?></td>
									<td><?php echo $this->__("Zencart");?></td>
								</tr>
							<?php } ?>
						<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	jQuery(document).ready(function () {
		dataTable = jQuery('#dataTables-example').dataTable({
			"aaSorting": [[0, 'desc']],
		});
	});
</script>